version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    volumes:
      - ./frontend/front:/app
    
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./backend/back:/app
